# Generated by Django 5.1.5 on 2025-01-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstName', models.CharField(max_length=50, verbose_name='نام')),
                ('lastName', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('userName', models.CharField(max_length=20, unique=True, verbose_name='نام کاربری')),
                ('nCode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='کد ملی')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('homeNumber', models.CharField(max_length=10, verbose_name='شماره ثابت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شماره',
                'verbose_name_plural': 'شماره ها',
            },
        ),
    ]
