# Generated by Django 5.0.11 on 2025-01-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
