# Generated by Django 5.0.11 on 2025-01-17 09:43

import HR.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR', '0002_delete_phone_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityTitle', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('IsCapital', models.BooleanField(default=False, verbose_name='مرکز استان است؟')),
                ('CityCode', models.CharField(blank=True, max_length=4, null=True, verbose_name='کد شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProvinceTitle', models.CharField(max_length=50, unique=True, verbose_name='نام استان')),
                ('AbbreviationCode', models.CharField(blank=True, max_length=2, null=True, verbose_name='کد استان')),
                ('PhoneCode', models.IntegerField(blank=True, null=True, verbose_name='پیش شماره استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistrictTitle', models.CharField(max_length=50, verbose_name='نام منطقه')),
                ('City', models.ForeignKey(default=103, on_delete=django.db.models.deletion.CASCADE, to='HR.city', verbose_name='شهر مربوطه')),
            ],
            options={
                'verbose_name': 'ناحیه شهری',
                'verbose_name_plural': 'نواحی شهری',
            },
        ),
        migrations.CreateModel(
            name='ConstValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=50, verbose_name='عنوان')),
                ('Code', models.CharField(max_length=100, verbose_name='کد')),
                ('IsActive', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('OrderNumber', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='شماره ترتیب')),
                ('ConstValue', models.IntegerField(blank=True, null=True, verbose_name='مقدار مربوطه')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.constvalue', verbose_name='شناسه پدر')),
            ],
            options={
                'verbose_name': 'مقدار ثابت',
                'verbose_name_plural': 'مقادیر ثابت',
                'ordering': ['Parent_id', 'OrderNumber'],
            },
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('AddressText', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('No', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک')),
                ('UnitNo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره واحد')),
                ('PostalCode', models.BigIntegerField(blank=True, null=True, validators=[HR.validator.Validator.PostalCode], verbose_name='کد پستی')),
                ('IsDefault', models.BooleanField(default=False, verbose_name='آدرس پیش فرض است؟')),
                ('City', models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر محل زندگی')),
                ('CityDistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.citydistrict', verbose_name='منطقه')),
            ],
            options={
                'verbose_name': 'آدرس پستی',
                'verbose_name_plural': 'آدرس های پستی',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='Province',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.province', verbose_name='استان مربوطه'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserName', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='نام کاربری')),
                ('FirstName', models.CharField(max_length=200, verbose_name='نام')),
                ('LastName', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('FirstNameEnglish', models.CharField(blank=True, max_length=80, null=True, verbose_name='نام لاتین')),
                ('LastNameEnglish', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی لاتین')),
                ('FatherName', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام پدر')),
                ('ContractDate', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری')),
                ('ContractEndDate', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری')),
                ('About', models.CharField(blank=True, max_length=1000, null=True, verbose_name='درباره من')),
                ('Gender', models.BooleanField(default=False, verbose_name='جنسیت')),
                ('CVFile', models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل رزومه')),
                ('NumberOfChildren', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='تعداد فرزند')),
                ('NationalCode', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی')),
                ('BirthDate', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('IdentityNumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه')),
                ('IdentityRegisterDate', models.DateField(null=True, verbose_name='تاریخ صدور شناسنامه')),
                ('IdentitySerialNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='سریال شناسنامه')),
                ('InsuranceNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره بیمه')),
                ('IsActive', models.BooleanField(default=True, verbose_name='کاربر فعال است؟')),
                ('BirthCity', models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر محل تولد')),
                ('ContractType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ContractType', to='HR.constvalue', verbose_name='نوع قرارداد')),
                ('DegreeType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name='آخرین مقطع تحصیلی')),
                ('IdentityCity', models.ForeignKey(default=103, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='IdentityCity', to='HR.city', verbose_name='شهر محل صدور شناسنامه')),
                ('LastBuilding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersBuilding', to='HR.constvalue')),
                ('LastFloor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersFloor', to='HR.constvalue')),
                ('LivingAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.postaladdress', verbose_name='آدرس محل سکونت')),
                ('MarriageStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UsersMarriageStatus', to='HR.constvalue', verbose_name='وضعیت تاهل')),
                ('MilitaryStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UsersMilitaryStatus', to='HR.constvalue', verbose_name='وضعیت خدمت')),
                ('Religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UsersReligion', to='HR.constvalue', verbose_name='دین')),
                ('UserStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserStatus', to='HR.constvalue', verbose_name='وضعیت کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='فرد'),
        ),
    ]
