# Generated by Django 5.0.11 on 2025-01-17 10:02

import HR.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته های تحصیلی',
                'ordering': ('Title',),
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, verbose_name='ادرس ایمیل')),
                ('Title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('IsDefault', models.BooleanField(default=False, verbose_name='آدرس ایمیل پیشفرض است؟')),
                ('Person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.users', verbose_name='فرد')),
            ],
            options={
                'verbose_name': 'آدرس پست الکترونیکی',
                'verbose_name_plural': 'آدرس های پست الکترونیکی',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TelNumber', models.BigIntegerField(help_text=' شماره ثابت بدون داخلی وارد شود. (مثلا : 87654321) شماره موبایل بدون صفر وارد شود مثلاً 9121234567', verbose_name='شماره تماس')),
                ('Title', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('IsDefault', models.BooleanField(default=False, verbose_name='پیش فرض')),
                ('Person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='HR.users', verbose_name='فرد')),
                ('Province', models.ForeignKey(blank=True, default=103, help_text='این فیلد زمانی پر می شود که تلفن خط ثابت باشد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.province', verbose_name='استان')),
                ('TelType', models.ForeignKey(help_text='منظور از نوع این است که می تواند، محل زندگی، همراه، ضروری و... باشد', on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره های تماس',
            },
        ),
        migrations.CreateModel(
            name='Tendency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='گرایش')),
                ('FieldOfStudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.fieldofstudy', verbose_name='گرایش تحصیلی')),
            ],
            options={
                'verbose_name': 'گرایش تحصیلی',
                'verbose_name_plural': 'گرایش های تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='نام دانشگاه')),
                ('UniversityCity', models.ForeignKey(default=103, on_delete=django.db.models.deletion.SET_DEFAULT, to='HR.city', verbose_name='شهر محل دانشگاه')),
                ('University_Type', models.ForeignKey(blank=True, limit_choices_to={'IsActive': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name='نوع دانشگاه')),
            ],
            options={
                'verbose_name': 'دانشگاه',
                'verbose_name_plural': 'دانشگاه ها',
            },
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('EndDate', models.DateField(blank=True, null=True, verbose_name='تاریخ خاتمه')),
                ('StartYear', models.PositiveSmallIntegerField(blank=True, help_text='تاریخ شمسی', null=True, validators=[HR.validator.Validator.YearNumber], verbose_name='سال ورود')),
                ('EndYear', models.PositiveSmallIntegerField(blank=True, help_text='تاریخ شمسی', null=True, validators=[HR.validator.Validator.YearNumber], verbose_name='سال فراغت از تحصیل')),
                ('IsStudent', models.BooleanField(default=False, verbose_name='دانشجو است؟')),
                ('GPA', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='معدل')),
                ('Degree_Type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR.constvalue', verbose_name=' مقطع تحصیلی')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='HR.users', verbose_name='پرسنل')),
                ('EducationTendency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HR.tendency', verbose_name='گرایش تحصیلی')),
                ('University', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.university', verbose_name='دانشگاه محل تحصیل')),
            ],
            options={
                'verbose_name': 'سابقه تحصیلی',
                'verbose_name_plural': 'سوابق تحصیلی',
            },
        ),
    ]
