# Generated by Django 5.0.11 on 2025-01-17 10:14

import HR.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_fieldofstudy_emailaddress_phonenumber_tendency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_UserTeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Superior', models.BooleanField(default=False, verbose_name='ارشد')),
                ('StartDate', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('EndDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'اطلاعات پرسنل',
                'verbose_name_plural': 'اطلاعات همه ی پرسنل',
                'db_table': 'V_UserTeamRole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewRoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleTitle', models.CharField(max_length=100, verbose_name='عنوان سمت')),
                ('HasLevel', models.BooleanField(default=False, verbose_name='آیا این سمت دارای سطح است؟')),
                ('HasSuperior', models.BooleanField(default=False, verbose_name='آیا این سمت دارای ارشد دارد؟')),
                ('AllowedTeams', models.CharField(max_length=1000, verbose_name='این سمت در چه تیم های فعال است؟')),
                ('RequestorId', models.CharField(max_length=10, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی درخواست دهنده')),
                ('RequestDate', models.DateField(auto_now_add=True, verbose_name='تاریخ ارائه درخواست')),
                ('ManagerId', models.CharField(max_length=10, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر درخواست دهنده')),
                ('ManagerOpinion', models.BooleanField(default=0, help_text='در صورت موافقت مقدار یک و در غیر این صورت صفر می باشد', verbose_name='نظر مدیر درخواست دهنده')),
                ('ManagerDate', models.DateField(null=True, verbose_name='تاریخ اظهار نظر مدیر درخواست دهنده')),
                ('CTOId', models.CharField(max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر عامل')),
                ('CTOOpinion', models.BooleanField(default=0, help_text='در صورت موافقت مقدار یک و در غیر این صورت صفر می باشد', null=True, verbose_name='نظر مدیر عامل')),
                ('CTODate', models.DateField(verbose_name='تاریخ اظهار نظر مدیرعامل')),
            ],
            options={
                'verbose_name': 'درخواست افزودن سمت جدید',
                'verbose_name_plural': 'درخواست افزودن سمت های جدید',
            },
        ),
        migrations.CreateModel(
            name='RoleGroupTargetException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleGroup', models.CharField(max_length=100, verbose_name='گروه مبدا')),
                ('RoleGroupTarget', models.CharField(max_length=100, verbose_name='گروه مقصد')),
            ],
            options={
                'verbose_name': 'گروه سمت',
                'verbose_name_plural': 'گروه های سمت ها',
            },
        ),
        migrations.CreateModel(
            name='RoleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelName', models.CharField(max_length=20, verbose_name='نام سطح')),
            ],
            options={
                'verbose_name': 'سطح',
                'verbose_name_plural': 'سطوح',
                'db_table': 'RoleLevel',
            },
        ),
        migrations.CreateModel(
            name='AccessPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AccessPersonnelUserNames', to='HR.users', verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'دسترسی انتخاب  سمت',
                'verbose_name_plural': 'دسترسی های انتخاب همه سمت ها',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleId', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد سمت')),
                ('RoleName', models.CharField(max_length=100, verbose_name='نام سمت')),
                ('HasLevel', models.BooleanField(default=False, verbose_name='دارای سطح')),
                ('HasSuperior', models.BooleanField(default=False, verbose_name='ارشد دارد')),
                ('Comment', models.CharField(max_length=200, null=True, verbose_name='توضیحات')),
                ('NewRoleRequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.newrolerequest', verbose_name='شناسه درخواست اضافه کردن سمت')),
            ],
            options={
                'verbose_name': 'سمت',
                'verbose_name_plural': 'سمت ها',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleGroup', models.CharField(max_length=50, verbose_name='گروه')),
                ('RoleGroupName', models.CharField(blank=True, max_length=100, null=True, verbose_name=' نام گروه')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RoleGroupRoleIDs', to='HR.role', verbose_name='سمت فعلی')),
            ],
            options={
                'verbose_name': 'گروه سمت',
                'verbose_name_plural': 'گروه های سمت ها',
            },
        ),
        migrations.CreateModel(
            name='OrganizationChartRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationChartRoleRoleIDs', to='HR.role', verbose_name='سمت')),
                ('LevelId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationChartRoleRoleLevels', to='HR.rolelevel', verbose_name='سطح ')),
            ],
            options={
                'verbose_name': 'سمت و سطح',
                'verbose_name_plural': 'سمت ها و سطح ها',
            },
        ),
        migrations.CreateModel(
            name='ChangeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Superior', models.BooleanField(default=False, verbose_name='وضعیت فعلی ارشد')),
                ('SuperiorTarget', models.BooleanField(default=False, verbose_name='وضعیت جدید ارشد')),
                ('Education', models.BooleanField(default=True, verbose_name='آموزش نیاز دارد؟')),
                ('Educator', models.CharField(blank=True, max_length=100, null=True, verbose_name='آموزش دهنده')),
                ('Evaluation', models.BooleanField(default=True, verbose_name='ارزیابی نیاز دارد؟')),
                ('Assessor', models.CharField(blank=True, max_length=100, null=True, verbose_name='ارزیابی کننده')),
                ('RequestGap', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان')),
                ('Assessor2', models.CharField(blank=True, max_length=100, null=True, verbose_name='ارزیابی کننده دوم')),
                ('ReEvaluation', models.BooleanField(default=True, verbose_name='ارزیابی  دوم نیاز دارد؟')),
                ('PmChange', models.BooleanField(default=True, verbose_name='تغیرات PM؟')),
                ('ITChange', models.BooleanField(default=True, verbose_name='تغیرات IT؟')),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChangeRoleRoleIDs', to='HR.role', verbose_name='سمت فعلی')),
                ('RoleIdTarget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChangeRoleRoleIdTargets', to='HR.role', verbose_name='سمت جدید')),
                ('LevelId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChangeRoleRoleLevels', to='HR.rolelevel', verbose_name='سطح فعلی')),
                ('LevelIdTarget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChangeRoleLevelIdTargets', to='HR.rolelevel', verbose_name='سطح جدید')),
            ],
            options={
                'verbose_name': 'اطلاعات تغییر سمت',
                'verbose_name_plural': 'اطلاعات تغییر سمت ها',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamCode', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='کدتیم')),
                ('TeamName', models.CharField(max_length=100, verbose_name='نام تیم')),
                ('ActiveInService', models.BooleanField(default=True, verbose_name=' کتاب')),
                ('ActiveInEvaluation', models.BooleanField(default=True, verbose_name='ارزیابی')),
                ('IsActive', models.BooleanField(default=True, verbose_name='آیا تیم فعال است؟')),
                ('GeneralManager', models.ForeignKey(help_text='مدیر عمومی می تواند، مدیر پروژه یا مدیر اداری، یا  مدیر اداری یا کلا هر مدیری باشد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamGeneralManager', to='HR.users', verbose_name='مدیر عمومی')),
                ('SupportManager', models.ForeignKey(help_text='برای تیم های عملیانی مشخص می شود و برای غیر عملیاتی ها نال است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamSupportManager', to='HR.users', verbose_name='مدیر پشتیبانی')),
                ('TestManager', models.ForeignKey(help_text='برای تیم های عملیانی مشخص می شود و برای غیر عملیاتی ها نال است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamTestManager', to='HR.users', verbose_name='مدیر تست')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='UserTeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Superior', models.BooleanField(default=False, verbose_name='ارشد')),
                ('StartDate', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('EndDate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان')),
                ('LevelId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.rolelevel', verbose_name='سطح')),
                ('ManagerUserName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserTeamRoleManagerUserNames', to='HR.users', verbose_name='نام مدیر')),
                ('RoleId', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='کد سمت')),
                ('TeamCode', models.ForeignKey(db_column='TeamCode', on_delete=django.db.models.deletion.CASCADE, to='HR.team', verbose_name='کدتیم')),
                ('UserName', models.ForeignKey(db_column='UserName', on_delete=django.db.models.deletion.CASCADE, related_name='UserTeamRoleUserNames', to='HR.users', verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'اطلاعات پرسنل',
                'verbose_name_plural': 'اطلاعات همه ی پرسنل',
                'db_table': 'UserTeamRole',
            },
        ),
    ]
