# Generated by Django 5.0.11 on 2025-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_payment_paymentaverage_paymentaverageyearly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamallowedroles',
            name='AllowedRoleCount',
            field=models.PositiveSmallIntegerField(default='100', null=True, verbose_name='تعداد مجاز'),
        ),
    ]
