# Generated by Django 5.0.11 on 2025-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_alter_teamallowedroles_allowedrolecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='setteamallowedrolerequest',
            name='DocId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه سند'),
        ),
        migrations.AddField(
            model_name='setteamallowedrolerequest',
            name='StatusCode',
            field=models.CharField(default='DRAFTR', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='setteamallowedrolerequest',
            name='CTODate',
            field=models.DateField(null=True, verbose_name='تاریخ اظهار نظر مدیرعامل'),
        ),
    ]
