# Generated by Django 5.0.11 on 2025-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_alter_newrolerequest_ctodate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrolerequest',
            name='StatusCode',
            field=models.CharField(choices=[('DRAFTR', 'پیش نویس'), ('MANREV', 'بررسی مدیر'), ('CTOREV', 'بررسی مدیر عامل'), ('FINSUC', 'خاتمه - تایید'), ('FINREJ', 'خاتمه - رد'), ('FAILD', 'خطا')], default='DRAFTR', max_length=6, null=True),
        ),
    ]
