# Generated by Django 5.0.11 on 2025-04-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_newrolerequest_statuscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrolerequest',
            name='ConditionsText',
            field=models.CharField(max_length=1000, null=True, verbose_name='این سمت چه شرایط احرازی دارد ؟'),
        ),
        migrations.AddField(
            model_name='newrolerequest',
            name='DutiesText',
            field=models.CharField(max_length=1000, null=True, verbose_name='این سمت چه شرایح شغلی دارد ؟'),
        ),
        migrations.AlterField(
            model_name='newrolerequest',
            name='StatusCode',
            field=models.CharField(choices=[('DRAFTR', 'پیش نویس'), ('MANREV', 'بررسی مدیر'), ('CTOREV', 'بررسی مدیر عامل'), ('FINSUC', 'خاتمه - تایید'), ('FINREJ', 'خاتمه - رد'), ('FAILED', 'خطا')], default='DRAFTR', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='setteamallowedrolerequest',
            name='StatusCode',
            field=models.CharField(choices=[('DRAFTR', 'پیش نویس'), ('MANREV', 'بررسی مدیر'), ('CTOREV', 'بررسی مدیر عامل'), ('FINSUC', 'خاتمه - تایید'), ('FINREJ', 'خاتمه - رد'), ('FAILED', 'خطا')], default='DRAFTR', max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='RoleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(db_column='Title', max_length=50, null=True, verbose_name='عنوان')),
                ('DescriptionType', models.CharField(choices=[('C', 'شرایط احراز'), ('D', 'شرح وظایف')], max_length=1, verbose_name='نوع')),
                ('RoleID', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, to='HR.role', verbose_name='شناسه سمت')),
            ],
            options={
                'verbose_name': 'دسته بندی سمت',
                'verbose_name_plural': 'دسته بندی های سمت',
            },
        ),
    ]
