# Generated by Django 5.0.11 on 2025-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0011_newrolerequest_conditionstext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrolerequest',
            name='DocId',
            field=models.IntegerField(blank=True, null=True, verbose_name='شناسه سند'),
        ),
        migrations.AddField(
            model_name='newrolerequest',
            name='RelevantManager',
            field=models.CharField(max_length=50, null=True, verbose_name='مدیر مربوطه'),
        ),
    ]
