# Generated by Django 5.0.11 on 2025-05-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_newrolerequest_docid_newrolerequest_relevantmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrolerequest',
            name='RoleTypeCode',
            field=models.CharField(choices=[('A', 'تحلیل گران'), ('P', 'برنامه نویسان'), ('T', 'تسترها'), ('S', 'پشتیبان'), ('M', 'مدیران'), ('O', 'سایرین')], max_length=1, null=True, verbose_name='نوع سمت'),
        ),
    ]
