# Generated by Django 5.0.11 on 2025-05-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_newrolerequest_roletypecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrolerequest',
            name='NewRoleTypeTitle',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان نوع سمت جدید'),
        ),
    ]
