# Generated by Django 5.0.11 on 2025-05-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_newrolerequest_newroletypetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrolerequest',
            name='ManagerTypeCode',
            field=models.CharField(choices=[('A', 'تحلیل گران'), ('P', 'برنامه نویسان'), ('T', 'تسترها'), ('S', 'پشتیبان'), ('M', 'مدیران'), ('O', 'سایرین')], max_length=1, null=True, verbose_name='کد نوع مدیر'),
        ),
        migrations.AlterField(
            model_name='newrolerequest',
            name='RoleTypeCode',
            field=models.CharField(choices=[('A', 'تحلیل گران'), ('P', 'برنامه نویسان'), ('T', 'تسترها'), ('S', 'پشتیبان'), ('M', 'مدیران'), ('O', 'سایرین')], max_length=1, null=True, verbose_name='کد نوع سمت'),
        ),
    ]
