# Generated by Django 5.0.11 on 2025-05-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0015_newrolerequest_managertypecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrolerequest',
            name='ManagerTypeCode',
        ),
        migrations.RemoveField(
            model_name='newrolerequest',
            name='RelevantManager',
        ),
        migrations.AddField(
            model_name='newrolerequest',
            name='ManagerType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.constvalue', verbose_name='مدیر مربوطه'),
        ),
    ]
