# Generated by Django 5.0.11 on 2025-05-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0016_remove_newrolerequest_managertypecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ManagerType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HR.constvalue', verbose_name='مدیر مربوطه'),
        ),
    ]
