# Generated by Django 5.0.11 on 2025-05-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0018_remove_newrolerequest_roletypecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrolerequest',
            name='ManagerType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_manager_type', to='HR.constvalue', verbose_name='مدیر مربوطه'),
        ),
        migrations.AlterField(
            model_name='newrolerequest',
            name='RoleType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_role_type', to='HR.constvalue', verbose_name='کد نوع سمت'),
        ),
    ]
