# Generated by Django 5.0.11 on 2025-05-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0019_alter_newrolerequest_managertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='RoleType',
            field=models.CharField(max_length=100, null=True, verbose_name='کد نوع سمت'),
        ),
        migrations.AlterField(
            model_name='role',
            name='ManagerType',
            field=models.CharField(max_length=100, null=True, verbose_name='مدیر مربوطه'),
        ),
    ]
