# Generated by Django 5.0.11 on 2025-05-09 21:03

import HR.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0020_role_roletype_alter_role_managertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_AllUserList',
            fields=[
                ('UserName', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='نام کاربری')),
                ('FirstName', models.CharField(max_length=200, verbose_name='نام')),
                ('LastName', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('ContractDate', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری')),
                ('NationalCode', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی')),
                ('TeamName', models.CharField(max_length=100, verbose_name='نام تیم')),
                ('RoleName', models.CharField(max_length=100, verbose_name='عنوان سمت')),
                ('UserActive', models.BooleanField(default=True, verbose_name='کاربر فعال است؟')),
                ('RoleActive', models.BooleanField(default=True, verbose_name='سمت کاربر فعال است؟')),
            ],
            options={
                'db_table': 'V_AllUserList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeCode', models.CharField(max_length=1)),
                ('TypeTitle', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'نوع سمت',
                'verbose_name_plural': 'نوع سمت ها',
                'db_table': 'HR_RoleType',
            },
        ),
        migrations.AddField(
            model_name='accesspersonnel',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='PersonNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='PersonNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='organizationchartteamrole',
            name='ManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='PersonNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='PersonNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='previoususerteamrole',
            name='ManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر'),
        ),
        migrations.AddField(
            model_name='previoususerteamrole',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='team',
            name='GeneralManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر عمومی'),
        ),
        migrations.AddField(
            model_name='team',
            name='SupportManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر پشتیبانی'),
        ),
        migrations.AddField(
            model_name='team',
            name='TestManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر تست'),
        ),
        migrations.AddField(
            model_name='users',
            name='BirthDateMiladi',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد میلادی'),
        ),
        migrations.AddField(
            model_name='users',
            name='ContractDateMiladi',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری میلادی'),
        ),
        migrations.AddField(
            model_name='users',
            name='ContractEndDateMiladi',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری میلادی'),
        ),
        migrations.AddField(
            model_name='userteamrole',
            name='ManagerNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی مدیر'),
        ),
        migrations.AddField(
            model_name='userteamrole',
            name='NationalCode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[HR.validator.Validator.NationalCode_Validator], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='users',
            name='BirthDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ContractDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ شروع همکاری'),
        ),
        migrations.AlterField(
            model_name='users',
            name='ContractEndDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ پایان همکاری'),
        ),
    ]
